### PR TITLE
Network param rename and market proposal fix

### LINKED ISSUE #302: Update perftest tool for new market changes
Update the perftest tool with correct renamed networks params and remove old field from market proposal structure.

### PR DESCRIPTION
**Pull request by peterbarrow**
Closes #302

### CODE REVIEW

**Review by ze97286 — APPROVED** [review]

File: perftest/wallet.go [hunk 1]
```diff
@@ -79,6 +79,10 @@ func (w walletWrapper) sendRequest(request []byte, token string) ([]byte, error)
 	defer resp.Body.Close()
 
 	if resp.StatusCode != 200 {
+		reply, err := io.ReadAll(resp.Body)
+		if err == nil {
+			fmt.Println(string(reply))
+		}
```
Comment (jeremyletang) [inline perftest/wallet.go:85]: did you expect to keep this?

Comment (peterbarrow) [reply perftest/wallet.go:85]: Yes, it dumps out the error if the wallet operation fails. It makes things easier when things go wrong. When things are fine it does nothing.
